In [2]:
import torch

In [9]:
N = 10
D_in = 1
D_out = 1
X = torch.randn(N,D_in)

liner_layer = torch.nn.Linear(in_features=D_in,out_features=D_out)

print(f"Layers Weight (W): {liner_layer.weight}\n")
print(f"Layer's Bias (b): {liner_layer.bias}\n")

y_hat_nn = liner_layer(X)

print(f"Output of nn.linear (first 3 rows ): \n{y_hat_nn[:3]}")

gelu = torch.nn.GELU()
sample = torch.randn(N)
activated_data = gelu(sample)
print(f"Sample Data: {sample}")
print(f"Activated Data: {activated_data}")


Layers Weight (W): Parameter containing:
tensor([[0.1342]], requires_grad=True)

Layer's Bias (b): Parameter containing:
tensor([-0.6508], requires_grad=True)

Output of nn.linear (first 3 rows ): 
tensor([[-0.6880],
        [-0.5903],
        [-0.6305]], grad_fn=<SliceBackward0>)
Sample Data: tensor([ 0.0969, -0.2493,  0.3619, -0.5613,  1.2562, -1.0934,  1.2796,  0.1856,
        -0.6504,  0.9097])
Activated Data: tensor([ 0.0522, -0.1001,  0.2321, -0.1613,  1.1249, -0.1499,  1.1512,  0.1065,
        -0.1676,  0.7446])
